{"name": "Demo failed test cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\testing\\steps\\login_feature.py\", line 40, in step_impl\n    assert False\n           ^^^^^\n"}, "steps": [{"name": "Given : Navigate to Home page", "status": "passed", "start": 1727306477551, "stop": 1727306478816}, {"name": "Then Fail the test case", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\testing\\steps\\login_feature.py\", line 40, in step_impl\n    assert False\n           ^^^^^\n"}, "start": 1727306478816, "stop": 1727306478816}], "attachments": [{"name": "failure_screenshot", "source": "28fc7cf2-0165-4d5e-a81d-1917f1adbac6-attachment.png", "type": "image/png"}], "start": 1727306477550, "stop": 1727306479026, "uuid": "a2ff15ba-a0cf-41d9-8ff8-b6b77ea9d626", "historyId": "ce7f5c9b51f1a8e229623049aeb7cdce", "fullName": "Search Functionality: Demo failed test cases", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Search Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}